// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyh2Vmw7Vy4a9ZfLDKVQxuKwJMS2IIxyM',
    appId: '1:919627250407:web:25e534f625ba5263944042',
    messagingSenderId: '919627250407',
    projectId: 'digital-earning-dc877',
    authDomain: 'digital-earning-dc877.firebaseapp.com',
    storageBucket: 'digital-earning-dc877.appspot.com',
    measurementId: 'G-NDJ7QRZ5N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfVau_-v2QY_CVeNOWpy2PDC_NIG9loY',
    appId: '1:919627250407:android:0e5d862ac46e24d6944042',
    messagingSenderId: '919627250407',
    projectId: 'digital-earning-dc877',
    storageBucket: 'digital-earning-dc877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyZpgjWczRsPm53Q4PnMDEcCwDA3z7Nw',
    appId: '1:919627250407:ios:903412b1d434e50c944042',
    messagingSenderId: '919627250407',
    projectId: 'digital-earning-dc877',
    storageBucket: 'digital-earning-dc877.appspot.com',
    iosBundleId: 'com.lexusdevelopers.digitalEarning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyZpgjWczRsPm53Q4PnMDEcCwDA3z7Nw',
    appId: '1:919627250407:ios:903412b1d434e50c944042',
    messagingSenderId: '919627250407',
    projectId: 'digital-earning-dc877',
    storageBucket: 'digital-earning-dc877.appspot.com',
    iosBundleId: 'com.lexusdevelopers.digitalEarning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyh2Vmw7Vy4a9ZfLDKVQxuKwJMS2IIxyM',
    appId: '1:919627250407:web:7023714fdc20b1ad944042',
    messagingSenderId: '919627250407',
    projectId: 'digital-earning-dc877',
    authDomain: 'digital-earning-dc877.firebaseapp.com',
    storageBucket: 'digital-earning-dc877.appspot.com',
    measurementId: 'G-E00GKG0YMD',
  );
}
